### PR TITLE
OpenBazaar added

### PR DESCRIPTION
**Pull request by Johan-Ng**

### CODE REVIEW

**Comment by deamme** [comment]
@Johan-Ng We changed `category` to `categories` which is now an array. Can you please make this change?

**Comment by Johan-Ng** [comment]
Ok

**Comment by deamme** [comment]
@Johan-Ng Should be like this `["E-commerce", "Shopping"]`

**Comment by Johan-Ng** [comment]
I've just changed it. Thanks for the advice

**Pull request merged**
