### PR TITLE
Added 2 links

### PR DESCRIPTION
**Pull request by Johan-Ng**
IanColeman and Alagoria added

### CODE REVIEW

**Comment by deamme** [comment]
Thanks for your PR! I think `https://iancoleman.io/bip39` is out of scope here, since we only want to list sites where you can actual spend your crypto to buy something (for now at least) 😄

**Comment by Johan-Ng** [comment]
Ok, I'll delete it. Thanks

**Comment by deamme** [comment]
@Johan-Ng Thanks! `Alagoria` was already added by  @premgwl before you, can you please delete that one?

**Comment by Johan-Ng** [comment]
Sure!

**Comment by deamme** [comment]
@Johan-Ng Sorry we have some conflicting changes. I would suggest making a new PR on a new branch which has the latest changes and then modify to accommodate the new changes. Sorry about that!

**Comment by Johan-Ng** [comment]
Ok

**Comment by deamme** [comment]
Closing this since #6

**Pull request closed without merging**
